name: Docker publish
on: [push]
jobs:
publish-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the hello-docker Docker image
run: |
       docker build . --tag ghcr.io/giswqs/hello-docker:latest
       docker run ghcr.io/giswqs/hello-docker:latest
       docker push ghcr.io/giswqs/hello-docker:latest


